# Generated by Django 5.1.4 on 2026-04-09 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=20)),
                ("modelo", models.CharField(max_length=30)),
                ("placa", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("Gabinete", "Gabinete"),
                            ("Comunicação", "Comunicação"),
                            ("Adjunto", "Adjunto"),
                            ("Ouvidoria", "Ouvidoria"),
                            ("Procon", "Procon"),
                            ("CODIS", "CODIS"),
                            ("COEPPIR", "COEPPIR"),
                            ("SEJUV", "SEJUV"),
                            ("SPM", "SPM"),
                            ("CPDH", "CPDH"),
                            ("CORDE", "CORDE"),
                            ("ASJUR", "ASJUR"),
                            ("UIAG", "UIAG"),
                            ("UIFP", "UIFP"),
                        ],
                        max_length=12,
                        verbose_name="Setor",
                    ),
                ),
                ("destino", models.CharField(max_length=100)),
                ("data_ida", models.DateField()),
                ("local_partida", models.TextField(default="SEMJIDH")),
                (
                    "horario_ida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de ida"
                    ),
                ),
                ("data_volta", models.DateField()),
                (
                    "horario_volta",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Previsão de retorno"
                    ),
                ),
                ("servidores", models.TextField()),
                ("solicitante", models.CharField(max_length=30)),
                ("processo", models.CharField(blank=True, max_length=23, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Atribuída", "Atribuída"),
                            ("Concluída", "Concluída"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.CharField(
                        choices=[
                            ("Carro (4 lugares)", "Carro (4 lugares)"),
                            ("Carro (6 lugares)", "Carro (6 lugares)"),
                            ("Ônibus", "Ônibus"),
                        ],
                        max_length=20,
                        verbose_name="Veículo",
                    ),
                ),
                (
                    "horario_volta_real",
                    models.TimeField(blank=True, null=True, verbose_name="Volta"),
                ),
                (
                    "carro",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.carro",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.motorista",
                    ),
                ),
            ],
        ),
    ]
