# Generated by Django 5.1.4 on 2025-02-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destino", models.CharField(max_length=100)),
                ("data_ida", models.DateField()),
                ("data_volta", models.DateField()),
                ("servidores", models.TextField()),
                ("solicitante", models.CharField(max_length=30)),
                ("processo", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Atribuída", "Atribuída"),
                            ("Concluída", "Concluída"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                ("criada_em", models.DateField(auto_now_add=True)),
                (
                    "motorista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.motorista",
                    ),
                ),
            ],
        ),
    ]
