# Generated by Django 5.1.4 on 2026-04-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE viagens_viagem ADD COLUMN horario_volta_real TIME;",
            reverse_sql="ALTER TABLE viagens_viagem DROP COLUMN horario_volta_real;"
        ),
    ]
