# Generated by Django 5.1.4 on 2026-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_inital.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='horario_volta_real',
            field=models.TimeField(null=True, blank=True, verbose_name='Volta'),
        ),
    ]